/**
 * Admin Dashboard Page
 *
 * Comprehensive administrative dashboard providing overview of system status,
 * user statistics, pending approvals, and recent activity.
 *
 * Enhanced with Phase 2 patterns:
 * - Toast notifications for user feedback
 * - WCAG 2.1 AA accessibility compliance
 * - Enhanced loading states with skeleton loaders
 *
 * Note: Infrastructure monitoring handled by AWS CloudWatch
 *
 * React 19: No memoization needed - React Compiler handles optimization
 *
 * @author Generated by GitHub Copilot
 */

import {
  Activity,
  ArrowDown,
  ArrowUp,
  Clock,
  RefreshCw,
  Shield,
  UserCheck,
  Users,
} from 'lucide-react';
import { useEffect, useState, type FC } from 'react';

import { useAuth } from '@domains/auth/context/AuthContext';
import { useErrorHandler } from '@hooks/errors/useErrorHandler';
import { useLocalization } from '@hooks/localization/useLocalization';
import { useToast } from '@hooks/useToast';
import { Skeleton } from '@shared/components/ui/Skeleton';
import Breadcrumb from '@shared/ui/Breadcrumb';
import ErrorAlert from '@shared/ui/ErrorAlert';
import { formatTime } from '@shared/utils';
import { adminService, auditService } from '../../../services/api';
import { HealthMonitoringDashboard } from '../components/HealthMonitoringDashboard';

// ============================================================================
// Types & Interfaces
// ============================================================================

interface AdminStats {
  total_users: number;
  active_users: number;
  pending_approvals: number;
}

interface AuditSummary {
  total_events: number;
  events_by_severity: { [key: string]: number };
  events_by_action: { [key: string]: number };
  recent_activity: Array<{
    action: string;
    timestamp: string;
    user_id?: string;
  }>;
}

interface StatCardProps {
  title: string;
  value: number | string;
  icon: React.ReactNode;
  trend?: {
    value: number;
    isPositive: boolean;
  };
  color: 'blue' | 'green' | 'yellow' | 'red' | 'purple';
  loading?: boolean;
}

// ============================================================================
// Components
// ============================================================================

const StatCard: FC<StatCardProps> = ({ title, value, icon, trend, color, loading = false }) => {
  const colorClasses = {
    blue: 'bg-blue-50 text-blue-600 border-blue-200',
    green: 'bg-green-50 text-green-600 border-green-200',
    yellow: 'bg-yellow-50 text-yellow-600 border-yellow-200',
    red: 'bg-red-50 text-red-600 border-red-200',
    purple: 'bg-purple-50 text-purple-600 border-purple-200',
  };

  if (loading) {
    return (
      <div className="section-container" role="status" aria-label="Loading statistics">
        <span className="sr-only">Loading {title}</span>
        <Skeleton className="h-4 w-24 mb-2" />
        <Skeleton className="h-8 w-16 mb-2" />
        <Skeleton className="h-3 w-16" />
      </div>
    );
  }

  return (
    <div
      className="section-container"
      role="group"
      aria-labelledby={`stat-${title.replace(/\s+/g, '-')}`}
    >
      <div className="flex items-center">
        <div className={`p-3 rounded-lg ${colorClasses[color]}`} aria-hidden="true">
          {icon}
        </div>
        <div className="ml-4 flex-1">
          <p
            id={`stat-${title.replace(/\s+/g, '-')}`}
            className="text-sm font-medium text-gray-600"
          >
            {title}
          </p>
          <div className="flex items-end">
            <p className="text-2xl font-semibold text-gray-900" aria-label={`${value} ${title}`}>
              {value}
            </p>
            {trend && (
              <div
                className={`ml-2 flex items-center text-sm ${
                  trend.isPositive ? 'text-green-600' : 'text-red-600'
                }`}
                aria-label={`Trend: ${trend.isPositive ? 'increased' : 'decreased'} by ${Math.abs(trend.value)} percent`}
              >
                {trend.isPositive ? (
                  <ArrowUp className="w-3 h-3" aria-hidden="true" />
                ) : (
                  <ArrowDown className="w-3 h-3" aria-hidden="true" />
                )}
                <span className="ml-1">{Math.abs(trend.value)}%</span>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

// ============================================================================
// Main Component
// ============================================================================

const AdminDashboardPage: FC = () => {
  const { hasPermission } = useAuth();
  const { error, handleError, clearError } = useErrorHandler();
  const { t } = useLocalization();
  const { toast } = useToast();

  // State
  const [adminStats, setAdminStats] = useState<AdminStats | null>(null);
  const [auditSummary, setAuditSummary] = useState<AuditSummary | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isRefreshing, setIsRefreshing] = useState(false);

  // Check permissions
  const canViewAdminData = hasPermission('admin') || hasPermission('admin:read');
  const canViewAuditLogs = hasPermission('audit:read') || hasPermission('admin');

  // ============================================================================
  // Data Loading Functions
  // ============================================================================
  // React 19 Compiler handles memoization

  const loadAdminStats = async () => {
    if (!canViewAdminData) return;

    try {
      const stats = (await adminService.getStats()) as AdminStats;
      setAdminStats(stats);
    } catch (error) {
      handleError(error, 'Failed to load admin statistics');
      toast.error('Failed to load admin statistics');
    }
  };

  const loadAuditSummary = async () => {
    if (!canViewAuditLogs) return;

    try {
      const summaryData = await auditService.getAuditSummary();
      // Map API response to local type structure
      const summary: AuditSummary = {
        total_events: summaryData.total_logs || 0,
        events_by_severity: {},
        events_by_action: {},
        recent_activity:
          summaryData.recent_actions?.map((log) => ({
            action: log.action,
            timestamp: log.timestamp,
            user_id: log.user_id,
          })) || [],
      };
      setAuditSummary(summary);
    } catch (error) {
      handleError(error, 'Failed to load audit summary');
      toast.error('Failed to load audit summary');
    }
  };

  const loadAllData = async () => {
    setIsLoading(true);
    clearError();

    try {
      await Promise.all([loadAdminStats(), loadAuditSummary()]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleRefresh = async () => {
    setIsRefreshing(true);
    try {
      await loadAllData();
      toast.success('Dashboard refreshed successfully');
    } finally {
      setIsRefreshing(false);
    }
  };

  // ============================================================================
  // Effects
  // ============================================================================

  useEffect(() => {
    loadAllData();
  }, [loadAllData]);

  // ============================================================================
  // Render
  // ============================================================================

  if (!canViewAdminData) {
    return (
      <div className="min-h-screen bg-gray-50 py-8">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center py-12">
            <Shield className="w-12 h-12 text-gray-400 mx-auto mb-4" />
            <h3 className="text-lg font-medium text-gray-900 mb-2">
              {t('dashboard.accessRestricted')}
            </h3>
            <p className="text-gray-600">{t('dashboard.noPermission')}</p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Header */}
        <div className="mb-8">
          <Breadcrumb />
          <div className="mt-4 flex items-center justify-between">
            <div>
              <h1 className="text-2xl font-bold text-gray-900">{t('dashboard.title')}</h1>
              <p className="text-gray-600 mt-1">{t('dashboard.description')}</p>
            </div>
            <button
              onClick={handleRefresh}
              disabled={isRefreshing}
              className="inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 disabled:opacity-50"
              aria-label={isRefreshing ? 'Refreshing dashboard data' : 'Refresh dashboard data'}
            >
              <RefreshCw
                className={`w-4 h-4 mr-2 ${isRefreshing ? 'animate-spin' : ''}`}
                aria-hidden="true"
              />
              {t('dashboard.refresh')}
            </button>
          </div>
        </div>

        {/* Error Alert */}
        {error && (
          <div className="mb-6">
            <ErrorAlert error={error} onDismiss={clearError} />
          </div>
        )}

        {/* Stats Grid */}
        {adminStats && (
          <div
            className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8"
            role="region"
            aria-label="Admin statistics overview"
          >
            <StatCard
              title={t('dashboard.totalUsers')}
              value={adminStats.total_users}
              icon={<Users className="w-6 h-6" />}
              color="blue"
              loading={isLoading}
            />
            <StatCard
              title={t('dashboard.activeUsers')}
              value={adminStats.active_users}
              icon={<UserCheck className="w-6 h-6" />}
              color="green"
              loading={isLoading}
            />
            <StatCard
              title={t('dashboard.pendingApprovals')}
              value={adminStats.pending_approvals}
              icon={<Clock className="w-6 h-6" />}
              color="yellow"
              loading={isLoading}
            />
          </div>
        )}

        {/* Health Monitoring Dashboard */}
        <div className="mb-8" role="region" aria-label="System health monitoring">
          <HealthMonitoringDashboard />
        </div>

        {/* Recent Activity */}
        {canViewAuditLogs && auditSummary && (
          <div className="card-white" role="region" aria-labelledby="recent-activity-title">
            <div className="px-6 py-4 border-b border-gray-200">
              <div className="flex items-center">
                <Activity className="w-5 h-5 text-purple-600 mr-2" aria-hidden="true" />
                <h3 id="recent-activity-title" className="text-lg font-medium text-gray-900">
                  {t('dashboard.recentActivity')}
                </h3>
                <span
                  className="ml-auto text-sm text-gray-500"
                  aria-label={`${auditSummary.total_events} total events`}
                >
                  {auditSummary.total_events} {t('dashboard.totalEvents')}
                </span>
              </div>
            </div>
            <div className="p-6">
              {isLoading ? (
                <div className="space-y-3" role="status" aria-label="Loading recent activity">
                  <span className="sr-only">Loading recent audit activity</span>
                  {Array.from({ length: 5 }).map((_, i) => (
                    <Skeleton key={`skeleton-${i}`} className="h-4 w-full" />
                  ))}
                </div>
              ) : auditSummary.recent_activity.length > 0 ? (
                <div className="space-y-3" role="list" aria-label="Recent audit activities">
                  {auditSummary.recent_activity.slice(0, 5).map((activity, index) => (
                    <div
                      key={`activity-${activity.timestamp}-${index}`}
                      role="listitem"
                      className="flex items-center justify-between py-2 border-b border-gray-100 last:border-0"
                      aria-label={`${activity.action}${activity.user_id ? ` by ${activity.user_id}` : ''} at ${formatTime(activity.timestamp)}`}
                    >
                      <div className="flex items-center">
                        <div className="w-2 h-2 bg-blue-400 rounded-full mr-3" aria-hidden="true" />
                        <span className="text-sm text-gray-900">{activity.action}</span>
                        {activity.user_id && (
                          <span className="text-xs text-gray-500 ml-2">by {activity.user_id}</span>
                        )}
                      </div>
                      <span className="text-xs text-gray-500">
                        {formatTime(activity.timestamp)}
                      </span>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="text-sm text-gray-500" role="status">
                  {t('dashboard.noRecentActivity')}
                </p>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default AdminDashboardPage;
