/**
 * GDPR Compliance API Service
 * Reference: API_COMPLETE_REFERENCE_PART2.md - GDPR Compliance APIs (Endpoints 32-38)
 *
 * Features:
 * - Data export (JSON/CSV formats) - GDPR Article 15 (Right of Access)
 * - Account deletion with grace period - GDPR Article 17 (Right to Erasure)
 * - Deletion cancellation during grace period
 * - Export status tracking with download links
 * - Consent management
 * - Data portability
 *
 * Rate Limits:
 * - POST /api/profile/gdpr/export: 5 requests/hour
 * - GET /api/profile/gdpr/export/{export_id}: 30 requests/minute
 * - POST /api/profile/gdpr/delete: 1 request/day
 * - POST /api/profile/gdpr/cancel-deletion: 5 requests/hour
 *
 * Grace Period:
 * - Account deletion has 24-hour grace period
 * - Use cancelAccountDeletion() to abort deletion during grace period
 *
 * @author Generated by GitHub Copilot
 */

import { apiClient } from '@lib/api/client';
import type {
  GDPRConsentResponse,
  GDPRDataPortabilityResponse,
  GDPRDeleteRequest,
  GDPRDeleteResponse,
  GDPRExportRequest,
  GDPRExportResponse,
  GDPRExportStatusResponse,
} from '@shared/types/api-complete.types';
import { logger } from '@shared/utils/logger';

/**
 * GDPR Service
 * Handles GDPR-related operations for data export and account deletion
 * Implements GDPR Article 15 (Right of Access) and Article 17 (Right to Erasure)
 */
export class GDPRService {
  // ============================================================================
  // DATA EXPORT (GDPR Article 15 - Right of Access)
  // ============================================================================

  /**
   * Export User Data
   * POST /api/profile/gdpr/export
   *
   * Export all personal data associated with the authenticated user.
   * Implements GDPR Article 15 - Right of Access
   *
   * Rate Limit: 5 requests per hour
   *
   * @param request - Export options (format, include_audit_logs, include_metadata)
   * @returns Export response with ID and status
   *
   * @example
   * const exportData = await gdprService.exportMyData({
   *   format: 'json',
   *   include_audit_logs: true,
   *   include_metadata: true
   * });
   * console.log(`Export ID: ${exportData.export_id}`);
   */
  async exportMyData(request?: GDPRExportRequest): Promise<GDPRExportResponse> {
    try {
      logger.debug('[GDPR] Requesting data export', { request });

      const response = await apiClient.execute<GDPRExportResponse>('/api/profile/gdpr/export', {
        method: 'POST',
        body: JSON.stringify(request || {}),
      });

      logger.info('[GDPR] Data export request successful', {
        exportId: response.export_id,
        status: response.status,
      });

      return response;
    } catch (error) {
      if (error instanceof Error) {
        logger.error('[GDPR] Failed to request data export', error);
      } else {
        logger.error('[GDPR] Failed to request data export');
      }
      throw error;
    }
  }

  /**
   * Check Export Status
   * GET /api/profile/gdpr/export/{export_id}
   *
   * Check the status of a data export request with download link.
   *
   * Rate Limit: 30 requests per minute
   *
   * @param exportId - Export ID from export request
   * @returns Export status, progress, and download link (if complete)
   *
   * @example
   * const status = await gdprService.checkExportStatus('export_abc123');
   * if (status.status === 'completed' && status.download_url) {
   *   console.log(`Download: ${status.download_url}`);
   *   console.log(`Expires: ${status.expires_at}`);
   * }
   */
  async checkExportStatus(exportId: string): Promise<GDPRExportStatusResponse> {
    try {
      logger.debug('[GDPR] Checking export status', { exportId });

      const status = await apiClient.execute<GDPRExportStatusResponse>(
        `/api/profile/gdpr/export/${exportId}`,
        { method: 'GET' }
      );

      logger.info('[GDPR] Export status retrieved', {
        exportId,
        status: status.status,
        progress: status.progress,
        hasDownloadUrl: Boolean(status.download_url),
      });

      return status;
    } catch (error) {
      if (error instanceof Error) {
        logger.error('[GDPR] Failed to check export status', error);
      } else {
        logger.error('[GDPR] Failed to check export status');
      }
      throw error;
    }
  }

  /**
   * Get Data Portability
   * GET /api/profile/gdpr/data-export
   *
   * Get immediate data export in portable format (no async processing).
   * Useful for small data sets or real-time portability requirements.
   *
   * Rate Limit: 10 requests per hour
   *
   * @param format - Export format ('json' or 'csv')
   * @returns User data in requested format
   *
   * @example
   * const data = await gdprService.getDataPortability('json');
   * console.log(`Exported at: ${data.exported_at}`);
   */
  async getDataPortability(format: 'json' | 'csv' = 'json'): Promise<GDPRDataPortabilityResponse> {
    try {
      logger.debug('[GDPR] Requesting data portability', { format });

      const response = await apiClient.execute<GDPRDataPortabilityResponse>(
        `/api/profile/gdpr/data-export?format=${format}`,
        { method: 'GET' }
      );

      logger.info('[GDPR] Data portability retrieved', {
        format: response.format,
        exportedAt: response.exported_at,
      });

      return response;
    } catch (error) {
      if (error instanceof Error) {
        logger.error('[GDPR] Failed to get data portability', error);
      } else {
        logger.error('[GDPR] Failed to get data portability');
      }
      throw error;
    }
  }

  // ============================================================================
  // ACCOUNT DELETION (GDPR Article 17 - Right to Erasure)
  // ============================================================================

  /**
   * Delete Account (Right to Erasure)
   * POST /api/profile/gdpr/delete
   *
   * Permanently delete user account and all personal data.
   * Implements GDPR Article 17 - Right to Erasure (Right to be Forgotten)
   *
   * **WARNING:** This action schedules PERMANENT deletion after 24-hour grace period!
   *
   * Rate Limit: 1 request per day
   *
   * @param request - Delete request with password, confirmation, and optional reason
   * @returns Deletion scheduled response with grace period info
   *
   * @example
   * const result = await gdprService.deleteMyAccount({
   *   password: 'CurrentPassword123!',
   *   confirmation: 'DELETE MY ACCOUNT',
   *   reason: 'No longer needed'
   * });
   * console.log(`Deletion scheduled. Grace period ends: ${result.grace_period_ends_at}`);
   * // Can cancel within 24 hours using cancelAccountDeletion()
   */
  async deleteMyAccount(request: GDPRDeleteRequest): Promise<GDPRDeleteResponse> {
    try {
      logger.warn('[GDPR] Account deletion requested');

      // Validate confirmation string for safety
      if (request.confirmation !== 'DELETE MY ACCOUNT') {
        throw new Error(
          'Invalid confirmation string. Must type exactly "DELETE MY ACCOUNT" to confirm.'
        );
      }

      const response = await apiClient.execute<GDPRDeleteResponse>('/api/profile/gdpr/delete', {
        method: 'POST',
        body: JSON.stringify(request),
      });

      logger.warn('[GDPR] Account deletion scheduled', {
        userId: response.user_id,
        scheduledAt: response.deletion_scheduled_at,
        gracePeriodEnds: response.grace_period_ends_at,
        finalDeletion: response.final_deletion_at,
      });

      return response;
    } catch (error) {
      if (error instanceof Error) {
        logger.error('[GDPR] Failed to delete account', error);
      } else {
        logger.error('[GDPR] Failed to delete account');
      }
      throw error;
    }
  }

  /**
   * Cancel Account Deletion
   * POST /api/profile/gdpr/cancel-deletion
   *
   * Cancel a scheduled account deletion during the 24-hour grace period.
   * After grace period expires, cancellation is no longer possible.
   *
   * Rate Limit: 5 requests per hour
   *
   * @returns Cancellation confirmation
   *
   * @example
   * const result = await gdprService.cancelAccountDeletion();
   * console.log(result.message); // "Account deletion cancelled successfully"
   */
  async cancelAccountDeletion(): Promise<{ message: string; cancelled_at: string }> {
    try {
      logger.info('[GDPR] Cancelling account deletion');

      const result = await apiClient.execute<{ message: string; cancelled_at: string }>(
        '/api/profile/gdpr/cancel-deletion',
        { method: 'POST' }
      );

      logger.info('[GDPR] Account deletion cancelled successfully', {
        cancelledAt: result.cancelled_at,
      });

      return result;
    } catch (error) {
      if (error instanceof Error) {
        logger.error('[GDPR] Failed to cancel account deletion', error);
      } else {
        logger.error('[GDPR] Failed to cancel account deletion');
      }
      throw error;
    }
  }

  // ============================================================================
  // CONSENT MANAGEMENT
  // ============================================================================

  /**
   * Get User Consents
   * GET /api/profile/gdpr/consents
   *
   * Retrieve all consent records for the current user.
   *
   * Rate Limit: 20 requests per minute
   *
   * @returns User consent records
   *
   * @example
   * const consents = await gdprService.getConsents();
   * consents.consents.forEach(c => {
   *   console.log(`${c.consent_type}: ${c.granted ? 'Granted' : 'Denied'}`);
   * });
   */
  async getConsents(): Promise<GDPRConsentResponse> {
    try {
      logger.debug('[GDPR] Fetching user consents');

      const consents = await apiClient.execute<GDPRConsentResponse>('/api/profile/gdpr/consents', {
        method: 'GET',
      });

      logger.info('[GDPR] User consents retrieved', {
        userId: consents.user_id,
        consentCount: consents.consents.length,
      });

      return consents;
    } catch (error) {
      if (error instanceof Error) {
        logger.error('[GDPR] Failed to fetch consents', error);
      } else {
        logger.error('[GDPR] Failed to fetch consents');
      }
      throw error;
    }
  }

  /**
   * Update User Consent
   * PUT /api/profile/gdpr/consents/{consent_type}
   *
   * Grant or revoke a specific consent.
   *
   * Rate Limit: 10 requests per minute
   *
   * @param consentType - Type of consent (e.g., 'marketing', 'analytics', 'third_party')
   * @param granted - Whether consent is granted
   * @returns Updated consent record
   *
   * @example
   * const result = await gdprService.updateConsent('marketing', true);
   * console.log(`Marketing consent granted at: ${result.granted_at}`);
   */
  async updateConsent(
    consentType: string,
    granted: boolean
  ): Promise<{ consent_type: string; granted: boolean; granted_at: string; version: string }> {
    try {
      logger.debug('[GDPR] Updating consent', { consentType, granted });

      const result = await apiClient.execute<{
        consent_type: string;
        granted: boolean;
        granted_at: string;
        version: string;
      }>(`/api/profile/gdpr/consents/${consentType}`, {
        method: 'PUT',
        body: JSON.stringify({ granted }),
      });

      logger.info('[GDPR] Consent updated successfully', {
        consentType,
        granted,
        grantedAt: result.granted_at,
      });

      return result;
    } catch (error) {
      if (error instanceof Error) {
        logger.error('[GDPR] Failed to update consent', error);
      } else {
        logger.error('[GDPR] Failed to update consent');
      }
      throw error;
    }
  }

  // ============================================================================
  // COMPLIANCE STATUS
  // ============================================================================

  /**
   * Get GDPR Compliance Status
   * GET /api/profile/gdpr/compliance-status
   *
   * Check GDPR compliance status for current user, including pending
   * deletions, active exports, and consent summary.
   *
   * Rate Limit: 10 requests per minute
   *
   * @returns GDPR compliance status information
   *
   * @example
   * const status = await gdprService.getComplianceStatus();
   * if (status.pending_deletion) {
   *   console.log('Account deletion scheduled!');
   * }
   */
  async getComplianceStatus(): Promise<{
    user_id: string;
    has_consents: boolean;
    pending_deletion: boolean;
    active_exports: number;
    last_export_at: string | null;
    data_retention_period: string;
  }> {
    try {
      logger.debug('[GDPR] Fetching GDPR compliance status');

      const status = await apiClient.execute<{
        user_id: string;
        has_consents: boolean;
        pending_deletion: boolean;
        active_exports: number;
        last_export_at: string | null;
        data_retention_period: string;
      }>('/api/profile/gdpr/compliance-status', { method: 'GET' });

      logger.info('[GDPR] GDPR compliance status retrieved', {
        userId: status.user_id,
        pendingDeletion: status.pending_deletion,
        activeExports: status.active_exports,
      });

      return status;
    } catch (error) {
      if (error instanceof Error) {
        logger.error('[GDPR] Failed to fetch compliance status', error);
      } else {
        logger.error('[GDPR] Failed to fetch compliance status');
      }
      throw error;
    }
  }
}

export const gdprService = new GDPRService();

export default gdprService;
