/**
 * RBAC API Service
 * Reference: API_COMPLETE_REFERENCE_PART2.md - RBAC & Role Management APIs (Endpoints 23-31)
 *
 * Features:
 * - Role CRUD operations (create, read, update, delete)
 * - Role hierarchy support (inherits_from, priority levels)
 * - Permission management (assign, revoke, list)
 * - User-role assignment/revocation
 * - RBAC cache management (stats, clear, sync)
 * - Comprehensive role metadata
 *
 * Rate Limits:
 * - GET /admin/roles: 30 requests/minute
 * - POST /admin/roles: 10 requests/minute
 * - PUT /admin/roles/{role_id}: 20 requests/minute
 * - DELETE /admin/roles/{role_id}: 5 requests/minute
 * - POST /admin/users/{user_id}/roles/{role_id}: 20 requests/minute
 * - DELETE /admin/users/{user_id}/roles/{role_id}: 20 requests/minute
 * - GET /admin/rbac/cache/stats: 10 requests/minute
 * - POST /admin/rbac/cache/clear: 5 requests/minute
 *
 * @author Generated by GitHub Copilot
 */

import { apiClient } from '@lib/api/client';
import type {
  AssignRoleResponse,
  CreateRoleRequest,
  DeleteRoleResponse,
  PermissionsResponse,
  RBACCacheStatsResponse,
  RevokeRoleResponse,
  RoleResponse,
  UpdateRoleRequest,
  UserPermissionsResponse,
} from '@shared/types/api-complete.types';
import { logger } from '@shared/utils/logger';

/**
 * RBAC Service
 * Handles role-based access control operations
 */
export class RBACService {
  // ============================================================================
  // ROLE MANAGEMENT
  // ============================================================================

  /**
   * List All Roles
   * GET /admin/roles
   *
   * Retrieve all roles in the system with permissions and hierarchy.
   *
   * @returns All roles with full details
   *
   * @example
   * const roles = await rbacService.listRoles();
   * roles.forEach(role => {
   *   console.log(`${role.role_name}: ${role.permissions.length} permissions`);
   * });
   */
  async listRoles(): Promise<RoleResponse[]> {
    try {
      logger.debug('[RBAC] Listing all roles');

      const roles = await apiClient.execute<RoleResponse[]>('/admin/roles', { method: 'GET' });

      logger.info('[RBAC] Roles fetched successfully', { count: roles.length });

      return roles;
    } catch (error) {
      if (error instanceof Error) {
        logger.error('[RBAC] Failed to list roles', error);
      } else {
        logger.error('[RBAC] Failed to list roles');
      }
      throw error;
    }
  }

  /**
   * Get Role Details
   * GET /admin/roles/{role_id}
   *
   * Retrieve detailed information about a specific role.
   *
   * @param roleId - Role identifier (role_name or role_id)
   * @returns Role details with permissions and hierarchy
   *
   * @example
   * const role = await rbacService.getRole('admin');
   */
  async getRole(roleId: string): Promise<RoleResponse> {
    try {
      logger.debug('[RBAC] Fetching role details', { roleId });

      const role = await apiClient.execute<RoleResponse>(`/admin/roles/${roleId}`, {
        method: 'GET',
      });

      logger.info('[RBAC] Role details fetched successfully', { roleId, roleName: role.role_name });

      return role;
    } catch (error) {
      if (error instanceof Error) {
        logger.error('[RBAC] Failed to get role', error);
      } else {
        logger.error('[RBAC] Failed to get role');
      }
      throw error;
    }
  }

  /**
   * Create Role
   * POST /admin/roles
   *
   * Create a new role with permissions and optional hierarchy.
   *
   * @param payload - Role creation data
   * @returns Created role
   *
   * @example
   * const newRole = await rbacService.createRole({
   *   role_name: 'content_editor',
   *   description: 'Content editing and publishing',
   *   permissions: ['content:read', 'content:write', 'content:publish'],
   *   priority: 50,
   *   inherits_from: ['user'],
   *   metadata: { department: 'marketing' }
   * });
   */
  async createRole(payload: CreateRoleRequest): Promise<RoleResponse> {
    try {
      logger.debug('[RBAC] Creating role', { roleName: payload.role_name });

      const role = await apiClient.execute<RoleResponse>('/admin/roles', {
        method: 'POST',
        body: JSON.stringify(payload),
      });

      logger.info('[RBAC] Role created successfully', {
        roleId: role.role_id,
        roleName: role.role_name,
      });

      return role;
    } catch (error) {
      if (error instanceof Error) {
        logger.error('[RBAC] Failed to create role', error);
      } else {
        logger.error('[RBAC] Failed to create role');
      }
      throw error;
    }
  }

  /**
   * Update Role
   * PUT /admin/roles/{role_id}
   *
   * Update role properties, permissions, or hierarchy.
   *
   * @param roleId - Role identifier
   * @param payload - Update data
   * @returns Updated role
   *
   * @example
   * const updated = await rbacService.updateRole('content_editor', {
   *   permissions: ['content:read', 'content:write', 'content:publish', 'content:delete'],
   *   priority: 60
   * });
   */
  async updateRole(roleId: string, payload: UpdateRoleRequest): Promise<RoleResponse> {
    try {
      logger.debug('[RBAC] Updating role', { roleId });

      const role = await apiClient.execute<RoleResponse>(`/admin/roles/${roleId}`, {
        method: 'PUT',
        body: JSON.stringify(payload),
      });

      logger.info('[RBAC] Role updated successfully', { roleId, roleName: role.role_name });

      return role;
    } catch (error) {
      if (error instanceof Error) {
        logger.error('[RBAC] Failed to update role', error);
      } else {
        logger.error('[RBAC] Failed to update role');
      }
      throw error;
    }
  }

  /**
   * Delete Role
   * DELETE /admin/roles/{role_id}
   *
   * Delete a role permanently. Users with this role will lose it.
   *
   * @param roleId - Role identifier
   * @returns Deletion confirmation
   *
   * @example
   * const result = await rbacService.deleteRole('old_role');
   */
  async deleteRole(roleId: string): Promise<DeleteRoleResponse> {
    try {
      logger.debug('[RBAC] Deleting role', { roleId });

      const result = await apiClient.execute<DeleteRoleResponse>(`/admin/roles/${roleId}`, {
        method: 'DELETE',
      });

      logger.info('[RBAC] Role deleted successfully', { roleId });

      return result;
    } catch (error) {
      if (error instanceof Error) {
        logger.error('[RBAC] Failed to delete role', error);
      } else {
        logger.error('[RBAC] Failed to delete role');
      }
      throw error;
    }
  }

  // ============================================================================
  // USER-ROLE ASSIGNMENT
  // ============================================================================

  /**
   * Assign Role to User
   * POST /admin/users/{user_id}/roles/{role_id}
   *
   * Assign a role to a user. User gains all role permissions.
   *
   * @param userId - User UUID
   * @param roleId - Role identifier
   * @returns Assignment confirmation
   *
   * @example
   * const result = await rbacService.assignRoleToUser('usr_123', 'manager');
   */
  async assignRoleToUser(userId: string, roleId: string): Promise<AssignRoleResponse> {
    try {
      logger.debug('[RBAC] Assigning role to user', { userId, roleId });

      const result = await apiClient.execute<AssignRoleResponse>(
        `/admin/users/${userId}/roles/${roleId}`,
        { method: 'POST' }
      );

      logger.info('[RBAC] Role assigned successfully', { userId, roleId });

      return result;
    } catch (error) {
      if (error instanceof Error) {
        logger.error('[RBAC] Failed to assign role', error);
      } else {
        logger.error('[RBAC] Failed to assign role');
      }
      throw error;
    }
  }

  /**
   * Remove Role from User
   * DELETE /admin/users/{user_id}/roles/{role_id}
   *
   * Revoke a role from a user. User loses role permissions.
   *
   * @param userId - User UUID
   * @param roleId - Role identifier
   * @returns Revocation confirmation
   *
   * @example
   * const result = await rbacService.removeRoleFromUser('usr_123', 'manager');
   */
  async removeRoleFromUser(userId: string, roleId: string): Promise<RevokeRoleResponse> {
    try {
      logger.debug('[RBAC] Removing role from user', { userId, roleId });

      const result = await apiClient.execute<RevokeRoleResponse>(
        `/admin/users/${userId}/roles/${roleId}`,
        { method: 'DELETE' }
      );

      logger.info('[RBAC] Role removed successfully', { userId, roleId });

      return result;
    } catch (error) {
      if (error instanceof Error) {
        logger.error('[RBAC] Failed to remove role', error);
      } else {
        logger.error('[RBAC] Failed to remove role');
      }
      throw error;
    }
  }

  /**
   * Get User Roles
   * GET /admin/users/{user_id}/roles
   *
   * Retrieve all roles assigned to a user.
   *
   * @param userId - User UUID
   * @returns User's roles
   *
   * @example
   * const roles = await rbacService.getUserRoles('usr_123');
   */
  async getUserRoles(userId: string): Promise<RoleResponse[]> {
    try {
      logger.debug('[RBAC] Fetching user roles', { userId });

      const roles = await apiClient.execute<RoleResponse[]>(`/admin/users/${userId}/roles`, {
        method: 'GET',
      });

      logger.info('[RBAC] User roles fetched successfully', {
        userId,
        count: roles.length,
      });

      return roles;
    } catch (error) {
      if (error instanceof Error) {
        logger.error('[RBAC] Failed to fetch user roles', error);
      } else {
        logger.error('[RBAC] Failed to fetch user roles');
      }
      throw error;
    }
  }

  /**
   * Get User Roles and Permissions
   * GET /admin/users/{user_id}/permissions
   *
   * Retrieve all roles and computed permissions for a user.
   *
   * @param userId - User UUID
   * @returns User's roles and aggregated permissions
   *
   * @example
   * const perms = await rbacService.getUserRolesAndPermissions('usr_123');
   * console.log(`Total permissions: ${perms.permissions.length}`);
   */
  async getUserRolesAndPermissions(userId: string): Promise<UserPermissionsResponse> {
    try {
      logger.debug('[RBAC] Fetching user roles and permissions', { userId });

      const permissions = await apiClient.execute<UserPermissionsResponse>(
        `/admin/users/${userId}/permissions`,
        { method: 'GET' }
      );

      logger.info('[RBAC] User permissions fetched successfully', {
        userId,
        permissionCount: permissions.permissions.length,
        roleCount: permissions.roles.length,
      });

      return permissions;
    } catch (error) {
      if (error instanceof Error) {
        logger.error('[RBAC] Failed to fetch user permissions', error);
      } else {
        logger.error('[RBAC] Failed to fetch user permissions');
      }
      throw error;
    }
  }

  // ============================================================================
  // PERMISSION MANAGEMENT
  // ============================================================================

  /**
   * List All Permissions
   * GET /admin/permissions
   *
   * Retrieve all available permissions grouped by category.
   *
   * @returns All system permissions
   *
   * @example
   * const perms = await rbacService.listPermissions();
   * console.log(`Categories: ${perms.categories.join(', ')}`);
   */
  async listPermissions(): Promise<PermissionsResponse> {
    try {
      logger.debug('[RBAC] Listing permissions');

      const permissions = await apiClient.execute<PermissionsResponse>('/admin/permissions', {
        method: 'GET',
      });

      logger.info('[RBAC] Permissions fetched successfully', {
        total: permissions.total,
        categories: permissions.categories.length,
      });

      return permissions;
    } catch (error) {
      if (error instanceof Error) {
        logger.error('[RBAC] Failed to list permissions', error);
      } else {
        logger.error('[RBAC] Failed to list permissions');
      }
      throw error;
    }
  }

  // ============================================================================
  // CACHE MANAGEMENT
  // ============================================================================

  /**
   * Get RBAC Cache Statistics
   * GET /admin/rbac/cache/stats
   *
   * Retrieve statistics about the RBAC cache performance.
   *
   * @returns Cache statistics
   *
   * @example
   * const stats = await rbacService.getCacheStats();
   * console.log(`Cache hit rate: ${stats.cache_hit_rate}%`);
   */
  async getCacheStats(): Promise<RBACCacheStatsResponse> {
    try {
      logger.debug('[RBAC] Fetching cache stats');

      const stats = await apiClient.execute<RBACCacheStatsResponse>('/admin/rbac/cache/stats', {
        method: 'GET',
      });

      logger.info('[RBAC] Cache stats fetched successfully', {
        cachedUsers: stats.total_cached_users,
        cachedRoles: stats.total_cached_roles,
        hitRate: stats.cache_hit_rate,
      });

      return stats;
    } catch (error) {
      if (error instanceof Error) {
        logger.error('[RBAC] Failed to fetch cache stats', error);
      } else {
        logger.error('[RBAC] Failed to fetch cache stats');
      }
      throw error;
    }
  }

  /**
   * Clear RBAC Cache
   * POST /admin/rbac/cache/clear
   *
   * Clear all RBAC cache entries. Use after bulk role/permission changes.
   *
   * @returns Confirmation message
   *
   * @example
   * const result = await rbacService.clearCache();
   */
  async clearCache(): Promise<{ message: string; cleared_at: string }> {
    try {
      logger.debug('[RBAC] Clearing cache');

      const result = await apiClient.execute<{ message: string; cleared_at: string }>(
        '/admin/rbac/cache/clear',
        { method: 'POST' }
      );

      logger.info('[RBAC] Cache cleared successfully');

      return result;
    } catch (error) {
      if (error instanceof Error) {
        logger.error('[RBAC] Failed to clear cache', error);
      } else {
        logger.error('[RBAC] Failed to clear cache');
      }
      throw error;
    }
  }

  /**
   * Sync RBAC Database
   * POST /admin/rbac/sync
   *
   * Synchronize RBAC cache with database. Use after direct DB modifications.
   *
   * @returns Synchronization result
   *
   * @example
   * const result = await rbacService.syncDatabase();
   */
  async syncDatabase(): Promise<{ message: string; synced_at: string }> {
    try {
      logger.debug('[RBAC] Syncing database');

      const result = await apiClient.execute<{ message: string; synced_at: string }>(
        '/admin/rbac/sync',
        { method: 'POST' }
      );

      logger.info('[RBAC] Database synced successfully');

      return result;
    } catch (error) {
      if (error instanceof Error) {
        logger.error('[RBAC] Failed to sync database', error);
      } else {
        logger.error('[RBAC] Failed to sync database');
      }
      throw error;
    }
  }
}

export const rbacService = new RBACService();

export default rbacService;
