// ========================================
// Services Data - Single Source of Truth
// ========================================

export const servicesData = {
  heroServices: [
    {
      id: 1,
      name: 'Web Development',
      description: 'Modern, responsive websites built with latest technologies',
      icon: '💻',
      price: 'From $2,999',
      duration: '2-4 weeks',
      popular: true,
    },
    {
      id: 2,
      name: 'Mobile App Development',
      description: 'Native and cross-platform mobile applications',
      icon: '📱',
      price: 'From $4,999',
      duration: '6-12 weeks',
      popular: false,
    },
    {
      id: 3,
      name: 'UI/UX Design',
      description: 'User-centered design that converts and delights',
      icon: '🎨',
      price: 'From $1,999',
      duration: '1-3 weeks',
      popular: false,
    },
  ],

  detailedServices: [
    {
      id: 1,
      name: 'Enterprise Solutions',
      category: 'Development',
      description: 'Scalable enterprise applications with advanced security and performance',
      features: [
        'Custom Architecture Design',
        'Advanced Security Implementation',
        'Performance Optimization',
        'Third-party Integrations',
        'Cloud Deployment',
        '24/7 Support & Maintenance',
      ],
      technologies: ['React', 'Node.js', 'AWS', 'Docker', 'TypeScript'],
      startingPrice: 15000,
      timeline: '12-24 weeks',
      complexity: 'Advanced',
      image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=400&fit=crop',
    },
    {
      id: 2,
      name: 'E-commerce Development',
      category: 'Development',
      description: 'Complete e-commerce solutions with payment processing and inventory management',
      features: [
        'Custom Shopping Cart',
        'Payment Gateway Integration',
        'Inventory Management',
        'Order Processing System',
        'Customer Analytics',
        'SEO Optimization',
      ],
      technologies: ['Next.js', 'Stripe', 'PostgreSQL', 'Redis', 'Tailwind'],
      startingPrice: 8000,
      timeline: '8-16 weeks',
      complexity: 'Intermediate',
      image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&h=400&fit=crop',
    },
    {
      id: 3,
      name: 'Brand Identity Design',
      category: 'Design',
      description: 'Complete brand identity including logo, guidelines, and marketing materials',
      features: [
        'Logo Design & Variations',
        'Brand Guidelines',
        'Color Palette & Typography',
        'Business Card Design',
        'Letterhead & Stationery',
        'Social Media Templates',
      ],
      technologies: ['Figma', 'Adobe Creative Suite', 'Sketch', 'Principle'],
      startingPrice: 3000,
      timeline: '3-6 weeks',
      complexity: 'Beginner',
      image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&h=400&fit=crop',
    },
    {
      id: 4,
      name: 'Digital Marketing',
      category: 'Marketing',
      description: 'Comprehensive digital marketing strategy to grow your online presence',
      features: [
        'SEO Strategy & Implementation',
        'Social Media Management',
        'Content Marketing',
        'PPC Campaign Management',
        'Email Marketing Automation',
        'Analytics & Reporting',
      ],
      technologies: ['Google Analytics', 'SEMrush', 'Mailchimp', 'Hootsuite'],
      startingPrice: 2500,
      timeline: '4-8 weeks',
      complexity: 'Intermediate',
      image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=400&fit=crop',
    },
    {
      id: 5,
      name: 'Mobile App Strategy',
      category: 'Consulting',
      description: 'Strategic consulting for mobile app development and market positioning',
      features: [
        'Market Research & Analysis',
        'Technology Stack Recommendation',
        'User Experience Strategy',
        'Monetization Strategy',
        'Go-to-Market Planning',
        'Competitive Analysis',
      ],
      technologies: ['Research Tools', 'Analytics Platforms', 'Prototyping Tools'],
      startingPrice: 5000,
      timeline: '2-4 weeks',
      complexity: 'Advanced',
      image: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=600&h=400&fit=crop',
    },
    {
      id: 6,
      name: 'API Development',
      category: 'Development',
      description: 'Robust and scalable API development for modern applications',
      features: [
        'RESTful API Design',
        'GraphQL Implementation',
        'Authentication & Authorization',
        'Rate Limiting & Caching',
        'API Documentation',
        'Testing & Monitoring',
      ],
      technologies: ['Node.js', 'Express', 'GraphQL', 'MongoDB', 'Jest'],
      startingPrice: 4000,
      timeline: '4-8 weeks',
      complexity: 'Intermediate',
      image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&h=400&fit=crop',
    },
  ],

  process: [
    {
      step: 1,
      title: 'Discovery & Planning',
      description: 'We understand your needs and create a detailed project roadmap',
      icon: '🔍',
      duration: '1-2 weeks',
    },
    {
      step: 2,
      title: 'Design & Prototyping',
      description: 'Create wireframes, mockups, and interactive prototypes',
      icon: '✏️',
      duration: '2-3 weeks',
    },
    {
      step: 3,
      title: 'Development & Testing',
      description: 'Build your solution with rigorous testing and quality assurance',
      icon: '⚡',
      duration: '4-12 weeks',
    },
    {
      step: 4,
      title: 'Launch & Support',
      description: 'Deploy your project and provide ongoing maintenance',
      icon: '🚀',
      duration: 'Ongoing',
    },
  ],

  testimonials: [
    {
      id: 1,
      name: 'Sarah Johnson',
      role: 'CEO, TechStart Inc.',
      content: 'Exceptional service and outstanding results. Our new website increased conversions by 150%.',
      avatar: '👩‍💼',
      rating: 5,
    },
    {
      id: 2,
      name: 'Michael Chen',
      role: 'Product Manager, InnovaCorp',
      content: 'Professional team that delivered exactly what we needed, on time and within budget.',
      avatar: '👨‍💻',
      rating: 5,
    },
    {
      id: 3,
      name: 'Emily Rodriguez',
      role: 'Marketing Director, GrowthCo',
      content: 'Their digital marketing strategy helped us reach new markets and double our online presence.',
      avatar: '👩‍🚀',
      rating: 5,
    },
  ],
};
